services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bycoderschallenge
      MYSQL_USER: bycoders
      MYSQL_PASSWORD: 123456
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10
      start_period: 10s
    ports:
      - "3307:3306"
    networks:
      - app-network

  api:
    build:
      context: ./  
    container_name: api
    ports:
      - "8080:8080"          # local:container Port
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=server=mysql;port=3306;database=ByCodersChallenge;user=root;password=123456
    networks:
      - app-network
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure

  web:
    build:
      context: ./ByCodersChallenge.WebApplication
    container_name: web
    ports:
      - "3000:80"            # Local port to access the website
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
