services:
  api:
    build:
      context: ./
    container_name: api
    ports:
      - "5000:8080"          # local:container Port
    environment:
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - app-network

  web:
    build:
      context: ./ByCodersChallenge.WebApplication
    container_name: web
    ports:
      - "8080:80"            # Local port to access the website
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
